# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY.
_commit: ff54ed7
_src_path: git@github.com:netboxlabs/netbox-plugin-scaffold.git
author_email: support@netboxlabs.com
author_name: NetBox Labs
branching_support: true
commercial: false
current_year: 2026
default_model_name: CustomScriptProject
default_model_verbose_name: customscriptproject
default_model_verbose_name_plural: customscriptprojects
dev_status: 2 - Pre-Alpha
django_version: '6.0'
github_org: netboxlabs
layout_style: subpackage
netbox_max_version: 4.7.99
netbox_min_version: 4.7.0
netbox_test_max_ref: v4.7.0-beta1
netbox_test_min_ref: v4.7.0-beta1
package_name: netbox_custom_scripts
plugin_name: NetBox Custom Scripts
python_version: '3.12'
python_versions:
- '3.12'
- '3.13'
- '3.14'
repo_slug: netbox-custom-scripts
ruff_version: 0.15.21
short_description: Custom Scripts for NetBox
version: 0.0.1
